// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    final envApiKey = dotenv.env['FIREBASE_API_KEY'] ?? android.apiKey;
    final envAppId = dotenv.env['FIREBASE_APP_ID'] ?? android.appId;
    final envMessagingSenderId = dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? android.messagingSenderId;
    final envProjectId = dotenv.env['FIREBASE_PROJECT_ID'] ?? android.projectId;
    final envDatabaseURL = dotenv.env['FIREBASE_DATABASE_URL'] ?? android.databaseURL;
    final envStorageBucket = dotenv.env['FIREBASE_STORAGE_BUCKET'] ?? android.storageBucket;

    final hasEnvOverride = dotenv.env['FIREBASE_API_KEY'] != null ||
        dotenv.env['FIREBASE_APP_ID'] != null ||
        dotenv.env['FIREBASE_PROJECT_ID'] != null ||
        dotenv.env['FIREBASE_DATABASE_URL'] != null;

    if (hasEnvOverride) {
      return FirebaseOptions(
        apiKey: envApiKey,
        appId: envAppId,
        messagingSenderId: envMessagingSenderId,
        projectId: envProjectId,
        databaseURL: envDatabaseURL,
        storageBucket: envStorageBucket,
      );
    }

    if (kIsWeb) {
      return android;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDA2THdnROYJyQZ7kH4YjHU9GM6omQpKQ',
    appId: '1:185569988747:android:24c5f0ddbc6c2fde21848e',
    messagingSenderId: '185569988747',
    projectId: 'local-vyapari-437e0',
    databaseURL: 'https://local-vyapari-437e0-default-rtdb.firebaseio.com',
    storageBucket: 'local-vyapari-437e0.firebasestorage.app',
  );
}
